# Simulação de relógio
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Robô 1
- ros_topic_name: "/robot1/joint_states"
  gz_topic_name: "/world/empty/model/robot1/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS



# Robô 2
- ros_topic_name: "/robot2/joint_states"
  gz_topic_name: "/world/empty/model/robot2/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS


# Robô 3
- ros_topic_name: "/robot3/joint_states"
  gz_topic_name: "/world/empty/model/robot3/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# Robô 4
- ros_topic_name: "/robot4/joint_states"
  gz_topic_name: "/world/empty/model/robot3/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

  # Robô 5
- ros_topic_name: "/robot5/joint_states"
  gz_topic_name: "/world/empty/model/robot3/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

#inutil
- ros_topic_name: "/robot/test_poses"
  gz_topic_name: "/world/empty/pose/info"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS



